### ISSUE TITLE
Bug: Matterport verlassen unmöglich

### ISSUE THREAD

**Issue by jakmeier** [bula21/mova21-app#115]
Wenn man in der App auf der Karte ein 360° 3D Modell öffnet, wie beispielsweise beim Bunker 13, dann öffnet sich eine Sicht mit Titel `Webcam "Bunker 13"`. Tippt man dann auf `3D-Bereich erkunden` dann kann man das Fenster danach nicht mehr schliessen.

Zurück Taste nützt auch nichts, die wird von ReactNative geschluckt und nicht an die Karte weitergegeben. Die einzige Lösung scheint ein kompletter Neustart des Apps zu sein.

Getestet auf Android und iPhone, nachdem ein Benutzer eine Anfrage an die Geschäftstelle gesendet hat. Im Webbrowser funktioniert es ohne Problem. Da hat es oben noch eine schwarze Zeile mit rechts einem weissen X zum Schliessen. Nicht so in der App.

![image](https://user-images.githubusercontent.com/6342444/182312798-6297d692-ccc2-48ad-a318-b0ee40441031.png)

**Comment by demianh** [comment]
Kann nicht in der App gefixt werden, wenn dann in der mova Map. Aber es wäre eh zu spät um noch ein Update zu machen... Bis die Updates ausgerollt sind, ist das Lager vorbei...
