### ISSUE TITLE
App Store Accounts aufsetzen

### ISSUE THREAD

**Issue by demianh** [bula21/mova21-app#15]
- [x] Apple App Store Account eröffnen
- [x] Google Play Store Account eröffnen

**Comment by hosts1** [comment]
@demianh 
Evtl hat die PBS bereits einen Account, dann könnte dieser benutzt werden. Vielleicht macht es aber sowieso Sinn kurz mit Safari/Kauri von der PBS das Thema anzusprechen.

Falls aus deiner Sicht nicht sinnvoll, dann die Accounts zumindest möglichst unter unserem "Verein Bundeslager 2021" aufsetzen und Zugriff sicherstellen. Es wäre mir wichtig, dass der Zugriff klar geregelt ist zu den Accounts.

**Comment by demianh** [comment]
Danke für die Inputs. Wenn die PBS schon Accounts hat wäre das natürlich noch einfacher (hab auf die schnelle aber nichts gefunden im App Store). Für den Verein Bundeslager 2021 müsste man zuerst noch eine DUNS Nummer beantragen, kostet zwar nichts ist aber etwas mühsam.
