### ISSUE TITLE
Wetter Seite

### ISSUE THREAD

**Issue by demianh** [bula21/mova21-app#2]
- [ ] Icon auf Startseite
- [ ] eigene Content Page

Im directus collection für Wetter erstellen:
- [ ] Dropdown für Wetter, Grad, Text, Datum
- [ ] Vorerfassen der Lagertage? Dann muss nur noch geändert werden.

Navigation: Pseudo Newseintrag in newsliste "Wetter " beim klick darauf, screens gemäss pdf

**Comment by Jonas-Marty** [comment]
https://bulacafe21.slack.com/files/UMRSVFS3G/F01J61XMP8D/app-screen_wetter_lay_02.pdf?origin_team=TCKFUJWNQ&origin_channel=CQMQQJHQV

https://files.slack.com/files-pri/TCKFUJWNQ-F01JMP1L0SV/download/mova_wetter-icons.zip

https://files.slack.com/files-pri/TCKFUJWNQ-F01J61YR0E9/download/mova_nav-icons_v04-original_radio-outline.svg

https://files.slack.com/files-pri/TCKFUJWNQ-F01J61YS3HB/download/mova_nav-icons_v04-original_radio.svg

**Comment by Jonas-Marty** [comment]
Im directus collection für Wetter erstellen: 
[ ] Dropdown für Wetter, Grad, Text, Datum
[ ] Vorerfassen der Lagertage? Dann muss nur noch geändert werden.
