### ISSUE TITLE
Directus auf v9 updaten

### ISSUE THREAD

**Issue by demianh** [bula21/mova21-app#27]
- [x] Update auf v9 in der cloud
- [x] Daten migrieren
- [x] App umstellen auf neues Backend
- [x] altes Backend abschalten

**Comment by jakmeier** [comment]
Eine neue Instanz auf Version 9 ist nun verfügbar: https://app-backend.mova.ch/
Diese ist an die skalierende Postgres DB angeschlossen.

Jemand hatta das ja schon vorbereitet, ich musste nur noch die environment variable `DB_SSL=true` setzen.

**Comment by demianh** [comment]
alles migriert 🎉
