### ISSUE TITLE
Veloverleih Mini App

### ISSUE THREAD

**Issue by demianh** [bula21/mova21-app#30]
Kleine mini Web App mit + - Buttons um die Counters für verleihbare Velos im Directus zu erhöhen für die Crew vom Veloverleih.

**Comment by Jonas-Marty** [comment]
Für Frontend vue.js, Auth mit Keycloak? --> oder basic auth

**Comment by Jonas-Marty** [comment]
auth.bula21.ch
clientid: tbd als ENV Variable
realm: master
redirecturl: tbd als ENV Variable
keycloak antwortet mit GET

Template für Pipeline:
https://github.com/bula21/mova21-logomat/blob/master/azure-pipeline.yml

Gruppe auf Keycloack muss noch erstellt werden, enthält Gruppe mit berechtigten Personen

**Comment by Jonas-Marty** [comment]
App rendert aktuell content von https://app-backend.mova.ch/admin/content/pages/10, sollte dann aber https://app-backend.mova.ch/admin/content/bike abrufen und darstellen
