### ISSUE TITLE
Sponsoren auf Loading Screen

### ISSUE THREAD

**Issue by demianh** [bula21/mova21-app#44]
Gemäss Mockup im Slack

- [x] Für iOS noch konfigurieren

**Comment by samuel0007** [comment]
Created a new branch feature/splashScreen, and with commit 90a5992 add basic splash screen with sponsors for Android. I couldn't find an elegant solution for correct scaling for now.

![Screenshot_20211022_150733_ch mova app](https://user-images.githubusercontent.com/26488655/138459020-43932d9e-f4ca-4c5b-8691-26691c75669a.jpg)

**Comment by demianh** [comment]
hmm, probably needs different images for different device sizes...

- [x] Also, the order needs to be changed to: Migros VS, Post, Mobiliar

**Comment by samuel0007** [comment]
Android: Adapted design to different device sizes, changed order

TODO:

- [ ] Language dependent (easy to do on Android with language specific assets)
- [ ] IOS

![image](https://user-images.githubusercontent.com/26488655/149656930-fb7da5cc-180a-4fb2-ad1f-ae0c5d8f9d53.png)
![image](https://user-images.githubusercontent.com/26488655/149656937-5c0ed42e-7c5a-46e7-abc7-675a0f00d352.png)

**Comment by demianh** [comment]
sieht gut aus, für iOS schaue ich es mir noch an

**Comment by demianh** [comment]
funktioniert jetzt auch auf iOS
