### ISSUE TITLE
Sponsoren Seite

### ISSUE THREAD

**Issue by demianh** [bula21/mova21-app#45]
Eine neue Sponsoren Infoseite gemäss dem Mockup im Slack. Einige Logos sind mehrsprachig, das sollte berücksichtigt werden. Liste der Sponsoren ist ebenfalls im Slack verlinkt.

Macht man vermutlich am einfachsten mit einem Custom Renderer.

**Comment by samuel0007** [comment]
Added renderer [9b08b44](https://github.com/bula21/mova21-app/commit/9b08b44e9afed545faaee695ed1c3eae0bdb2286)
Might have to update sponsor list in the future
