### ISSUE TITLE
Lexikon mit Pfadiwörtern / Übersetzungen

### ISSUE THREAD

**Issue by demianh** [bula21/mova21-app#49]
Mit Suchfunktion und Sprachauswahl

**Comment by samuel0007** [comment]
Basic display with sections
[9ef089a](https://github.com/bula21/mova21-app/commit/9ef089aaa5c39154c1e17c18c2f8691e2dd01e1a)
![image](https://user-images.githubusercontent.com/26488655/166719682-97c8fd41-e8fc-44ec-823f-3b39db4fc37f.png)
![image](https://user-images.githubusercontent.com/26488655/166719747-fdb5cde7-193d-4ef6-a8d6-164c1962df73.png)

Still todo:
- [ ] Searchbar
- [ ] Highlighting

**Comment by samuel0007** [comment]
https://github.com/bula21/mova21-app/pull/71

**Comment by demianh** [comment]
Als HTML reimplementiert, da Daten zu spät erhalten :(
