### ISSUE TITLE
Seiten innerhalb von anderen Seiten einbinden

### ISSUE THREAD

**Issue by jakmeier** [bula21/mova21-app#61]
Es wäre gut, wenn wir Infoseiten so erstellen können, dass sie nicht direkt in der Übersicht gelistet werden. Dafür muss man sie dann einbinden / verlinken können als Inhalt von anderen Seiten.
Damit können wir dann auch noch während dem Lager flexible auf neuen Inhalt eingehen. Beispielsweise für einzelne Standorte von Helferbeizen.

**Comment by demianh** [comment]
Habe es auf Prio 2 hochgestuft, da wir es für einige Inhaltsseiten benötigen
