### ISSUE TITLE
Radio Seite umsetzen

### ISSUE THREAD

**Issue by demianh** [bula21/mova21-app#8]
Folgendes ist bereits bekannt: 

- Audio stream ist ein Link zu einer Webseite mit einen mp3 stream (dynamisch)
- Meta Informationen: Statische Seite mit Programm vom Tag (aus Backend)
- Titel von ‘Sendung’ - z.B. "Morgens mit Scattle."

**Comment by demianh** [comment]
Diese Lib sieht gut aus: https://github.com/react-native-kit/react-native-track-player

**Comment by demianh** [comment]
Offene Punkte:

- [ ] Design gemäss Mockup
- [ ] iOS: Der Stream stottert sobald die App im Hintergrund ist (evtl. nur im Simulator)
- [ ] iOS: Beim ersten Mal Play drücken startet es nicht
- [ ] Android: Deeplinking auf Radio Seite bei

**Comment by samuel0007** [comment]
[feature/radio](https://github.com/bula21/mova21-app/tree/feature/radio)

![image](https://user-images.githubusercontent.com/26488655/168877604-70ebb7fc-9501-45a2-8231-6c66e587d476.png)
![image](https://user-images.githubusercontent.com/26488655/168877661-ea17bb20-40ec-4154-9ece-69368cffdc8e.png)
