### ISSUE TITLE
Bei Infoseitensuche auch Subpages finden und auflisten (und danach wieder ausblenden)

### ISSUE THREAD

**Issue by demianh** [bula21/mova21-app#84]
Sobald man sucht, auch subpages auflisten

**Comment by jakmeier** [comment]
Werden die denn nicht schon angezeigt? Ich meinte eigentlich, dass sie bei Suchresultaten angezeigt werden, also sobald man etwas in der Suche eingibt.

**Comment by demianh** [comment]
ja, jetzt wo ich es nochmals getestet habe, scheint es so zu sein 🤔 

Allerdings gibt es noch einen anderen Bug der mir grad aufgefallen ist:
Wenn man die Suche schliesst, werden weiterhin alle Subpages angezeigt.

**Comment by jakmeier** [comment]
https://github.com/bula21/mova21-app/pull/85 closes this

**Comment by demianh** [comment]
merged, thx :)
