### ISSUE TITLE
Meldung anzeigen wenn man offline Daten refreshed

### ISSUE THREAD

**Issue by demianh** [bula21/mova21-app#96]
Aktuell sieht es so aus, als wären die Daten neu geladen worden. Sinnvollerweise würde man einen Toast anzeigen, dass Daten nicht geladen wurden, wenn man offline ist. Zumindest, wenn man von Hand refreshed. 

Beim App Start ist die Meldung evtl. nicht unbedingt sinnvoll.

**Comment by jakmeier** [comment]
Mit #101 gibt es zwei Nachrichten: 
1. Keine Internetverbindung
2. Server unerreichbar trotz Internetverbindung

Die erste Nachricht wird bei allen Seiten angezeigt, wenn man aktualisiert. Beim wechseln der Seiten oder beim Neustart aber nicht.

Die zweite Fehlermeldung sollte man eigentlich nie sehen. Das wäre ein Zeichen dass was mit der Infrastruktur falsch ist. Im Moment würde diese Meldung bei jedem Versuch Daten zu laden angezeigt werden. Könnte man auch ändern, bin mir nicht sicher was Sinn macht.
